### ISSUE TITLE
If you disconnect and reconnect, all messages show as unread.

### ISSUE THREAD

**Issue by AshleySetter** [tdxvolt/tdxvolt-community#10]
If you disconnect and reconnect, all messages show as unread.

[Screencast from 16-05-24 14:52:37.webm](https://github.com/tdxvolt/tdxvolt-community/assets/14869658/ca09fdc1-0bb2-46d7-8b87-e1b2a14856a0)

**Comment by TobyEalden** [comment]
Yeah, at the moment the read receipts are stored in the browser, but they should probably be saved with the conversation on the Volt.

So if you were to sign in on a different machine (or even an incognito tab) it would show them all as unread too.

As a workaround, there is a 'mark all as read' option from the 'conversation' dropdown menu.

**Comment by TobyEalden** [comment]
Read receipts are now stored in the conversation database.
