### ISSUE TITLE
Support for direct pasting of images in chat

### ISSUE THREAD

**Issue by AshleySetter** [tdxvolt/tdxvolt-community#19]
Github and slack support directly pasting a copy-pasted image into the text box, if capturing screenshots that's helpful as I just capture screenshot and copy to clipboard and paste into the chat.

With watt currently I have to capture screenshot, save to a place on disk with a name, then go to watt and open the directory and then select the image I want.

**Comment by TobyEalden** [comment]
Done - but might need revisiting. Currently pasted images are stored as blobs directly in the message payload, which may cause the conversation loading to be sluggish if large images are used (although it will be cached after first load).
