### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by AshleySetter** [tdxvolt/tdxvolt-community#23]
The ability to form a block of text as a code block

e.g. in slack 
![image](https://github.com/tdxvolt/tdxvolt-community/assets/14869658/b50c4889-1b04-4369-8ae0-47d30ebd00df)

**Comment by TobyEalden** [comment]
For the time being - you should be able to use `<code>....</code>` or `<pre>...</pre>`.

**Comment by TobyEalden** [comment]
Done - message input toolbar now includes a code block button.

Also single backticks can be used too, `like this`.

Although strangely Hannah's keyboard seems to map a regular apostrophe to backtick -  Hannah can you confirm? If this is common we may need to disable the single backtick.

**Comment by HannahDalton** [comment]
I don't think it does???:
Back tik (key to left of 1) =  `
Apostrophe (underneath @) = ‘
Although is this dependant on which keyboard I am using - as was at home at the time

**Comment by TobyEalden** [comment]
Fixed.
