### ISSUE TITLE
Emoji delimiters

### ISSUE THREAD

**Issue by AshleySetter** [tdxvolt/tdxvolt-community#24]
Emoji's need to have some delimiters around them to designate you want an emoji otherwise you can't use text matching an emoji code (e.g. :3)

![image](https://github.com/tdxvolt/tdxvolt-community/assets/14869658/722d3d54-c6cf-4b59-abc2-f6df0e4d2892)

**Comment by TobyEalden** [comment]
Done - delimiters are semi-colon.
