### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by AshleySetter** [tdxvolt/tdxvolt-community#25]
Long text strings don't wrap, meaning you have to scroll a long way to the right to see them.

![image](https://github.com/tdxvolt/tdxvolt-community/assets/14869658/d8a9bae0-8831-4f3b-bd79-77a1fa32a6df)

**Comment by TobyEalden** [comment]
Done - probably won't apply retrospectively but any new messages should break on words if possible and if not just wrap.
